# Generated by Django 3.1.6 on 2022-05-04 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidos',
            new_name='Pedido',
        ),
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
