# Generated by Django 3.1.6 on 2022-05-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaApp', '0002_auto_20220504_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
