# Generated by Django 3.1.6 on 2022-05-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaApp', '0003_auto_20220504_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='LA FUCKING DIRECCION'),
        ),
    ]
