# Generated by Django 3.1.6 on 2022-05-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaApp', '0004_auto_20220504_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoContacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_razon', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('comuna', models.CharField(max_length=30)),
                ('comentario', models.CharField(max_length=255)),
            ],
        ),
    ]
